name: Prod Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: open-schools/open-schools-platform-frontend/.github/workflows/nextjs.yml@main
  #    secrets:
  #      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  #      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    secrets:
      HELP_REQUISITES: ${{ secrets.HELP_REQUISITES }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Prod deploy open-schools-platform-frontend
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.PROD_HOST}}
          user: "root"
          private_key: ${{secrets.PROD_PRIVATE_KEY}}
          command: |
            echo '--- START WORK ON REMOTE SERVER ---';
            set -e;

            echo '--- cd in project root ---';
            cd /opt/open-schools-platform-frontend;

            echo '--- CHECKOUT ON BRANCH ---';
            git checkout main;

            echo '--- Upgrade repo ---';
            git pull;                    

            echo '--- cd in schools dir ---';
            cd apps/schools;

            echo '--- Delete unused docker files ---';
            docker system prune --all --force;

            echo '--- Create prod image ---';
            docker build -f prod.Dockerfile -t nextjs-prod .;

            echo '--- cd in schools dir ---';
            cd /opt/open-schools-platform-frontend;

            echo '--- Force updating services ---';
            sh force-update-services.sh "prod";

            echo '--- Success! ---';
